### ISSUE TITLE
[FEATURE]: Please help, how to proxy all traffic to another socks5, So i can use it as middle proxy

### ISSUE THREAD

**Issue by johnson7788** [Amaindex/asyncio-socks-server#2]
**Is your feature request related to a problem? Please describe.**

- Server1:  Run Asyncio-socks-server, listen 2080

- Server2:  Run Asyncio-socks-server, listen 1080, transfer all traffic to Server1:2080

- my Desktop: Connect to Server2:1080

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Amaindex** [comment]
Hi @johnson7788 , sorry for long delay. 

For TCP, I think a traffic forwarding tool, such as `ssh` or `frp`, is all you need.
For example:
```
# On Server2
ssh -L 1080:Server1:2080 user@Server1
```

For UDP, the situation is somewhat complicated: `asyncio-socks-server` does not reuse UDP endpoints, but dynamically generates UDP endpoints during the service process, so it cannot be solved by the above method. But this situation may be improved in future versions.
